### ISSUE TITLE
Plugin doesn't work with ansible 2.4

### ISSUE THREAD

**Issue by compuguy** [adambullmer/sublime_ansible_vault#7]
Plugin doesn't seem to work on Ubuntu 17.04 with the latest Ansible 2.4. View vault just shows the command prompt output. Decrypt seems to do nothing.

Sublime Text version 3.0, Build 3143

**Comment by adambullmer** [comment]
Does it just open a blank view?

**Comment by compuguy** [comment]
View vault, results in a text file that shows the output if you enter `ansible-vault` in the command line. Decrypt does nothing (No errors in console either).

**Comment by shanedroid** [comment]
FWIW this behavior is the exact same as I noticed with #6, although I had first noticed it after updating to `ansible 2.3.2.0` I am currently using `ansible 2.4.0.0` and have been unable to figure out why it broke, tried troubleshooting various things.

**Comment by adambullmer** [comment]
It's possible there is a simple workaround until I can really dedicate the time to work on this. I've noticed that my editor window doesn't update on decrypt, but if I just click on the file in the project navigator, the page updates to the decrypted vault.

Hope this at least unblocks you guys for now.

**Comment by adambullmer** [comment]
Just cut a new release, it's usually available within a day on package control. Should fix the issues described in here. If not, hopefully a new error popup will show describing more of the problem. Thanks for your patience on this one.

**Comment by adambullmer** [comment]
Can anyone confirm if this is still an issue? Will probably close out at the end of the year if not.

**Comment by compuguy** [comment]
@adambullmer It might of partially fixed the issue. I will have to try it on the latest Ansible and Ubuntu 18.10.
